#!/bin/bash
# atom
cp ~/dotfiles/atom/colors.less ~/github/my-theme-syntax/styles/colors.less
# compton
cp ~/dotfiles/compton/compton.conf ~/.config/compton.conf
# conky
#cp ~/dotfiles/conky/miui ~/.conky/Conky\ MIUI/miui
# i3
# i3 scrips
cp -a ~/dotfiles/i3/scripts ~/.config/i3/scripts/
# i3 config
cp ~/dotfiles/i3/config ~/.config/i3/config
# i3 blocks
cp ~/dotfiles/i3/i3blocks.conf ~/.config/i3/i3blocks.conf
# rofi
cp ~/dotfiles/rofi/Pop-Dark.rasi /usr/share/rofi/themes/Pop-Dark.rasi
